---
slug: :open_your_url
depends:
  mikutter: '3.8'
  plugin:
  - command
  - gtk
  - gui
  - activity
version: '1.0'
author: cobodo
name: URLを開くやつ
description: URL指定でなんでも開けます。
repository: https://git.github.com/cobodo/open_your_url.git
